### ISSUE TITLE
clean up should gracefully handle phone numbers

### ISSUE THREAD

**Issue by mgoldey** [finos-voice/greenkey-asrtoolkit#22]
**Is your feature request related to a problem? Please describe.**
Phone numbers in transcripts are mapped to long series of numerals

**Describe the solution you'd like**
they should be mapped to spelled out single digits

Examples:

1-317-222-222 should map to the series of numbers 'one', 'three', 'one', 'seven', etc.

**Comment by ageojo** [comment]
`RE_PHONE = r'(\(?\d{3}\)?[\.\s|\-]?\d{3}[\.\s|\-]?\d{4})'`
