### ISSUE TITLE
wer script does not error with garbage files

### ISSUE THREAD

**Issue by cbrochtrup** [finos-voice/greenkey-asrtoolkit#59]
**Describe the bug**
The `wer` script accepts pretty much anything as input and will spit out a random WER. This conflates a problem with the wer script and a simple filename error. I would suggest adding 

**To Reproduce**
1. Run the wer script with any invalid input
2. Observe a lack of error and an output WER

```
> wer asdf asd
WER: 0.000%
> wer ^ ^
WER: 0.000%
> wer aaaaaaaaaaaaaaa eeeeeeeeeeeeeeeeeee
WER: 100.000%
> wer --ignore-nsns I-like to-eat-garbage
WER: 150.000%
> wer seg_data/gkt_corpora_earnings_test_AAPL2017q1TranscriptMturkTest_seg_0001. seg_data/gkt_corpora_earnings_test_AAPL2017q1TranscriptMturkTest_seg_0001.st
WER: 11.111%
```

**Expected behavior**
I would expect the `wer` script to error when given inputs that aren't valid ( ie. the expect file format, imaginary files, etc. )

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.5
 - Python version 3.5.2+

**Comment by cbrochtrup** [comment]
The fix should be easy.
- Check if files have valid extensions (.json, .stm, etc. )
- Check if files exist `import os.path; from os import; pathpath.isfile(input_arg)`

**Comment by mgoldey** [comment]
Agreed. This takes our tooling closer to maturity.

**Comment by mgoldey** [comment]
Ideally we should abstract these checks into some shared utils for our toolkit.
